### ISSUE TITLE
How to generate btree_s.csv?

### ISSUE THREAD

**Issue by Diksha-Moolchandani** [FindHao/drgpu#2]
The steps to generate btree_s.csv are unclear. I tried with the steps mentioned but it does not show "Source" in "View" tab. Still I  export as csv and try to use it to generate the tree. However, it gives key error: 

_raise KeyError(key) from err
KeyError: 'stall_barrier'_

Can you please help me with this issue?

**Comment by FindHao** [comment]
Sorry for the late reply. I just found your issue. 

>I tried with the steps mentioned but it does not show "Source" in "View" tab.

Have you compiled the btree via the makefile?

**Comment by Diksha-Moolchandani** [comment]
it is solved so I closed it. But I have another question.Will create new issue for that
