### ISSUE TITLE
A100.ini

### ISSUE THREAD

**Issue by Diksha-Moolchandani** [FindHao/drgpu#3]
Hi, 

I am trying to create a100.ini
May I know what is FB_THROUGHPUT_FIX? What does FB refer to?

Also would you suggest some link to find these specs for a100, specifically TLB information?

**Comment by FindHao** [comment]
`FB_THROUGHPUT_FIX = 1/ memory_bandwith * boost_clock`
https://github.com/FindHao/drgpu/blob/master/mem_config/gtx1650.ini#L17
It is a computed attribution to show the memory throughput. 

I can't remember the exact FB meaning here, but it is the same with GPU_MEMORY.

https://github.com/FindHao/drgpu/blob/6a1ddf4e177ad6023a5b7b2fdd65a73d8edb6362/counters.py#L93

**Comment by FindHao** [comment]
For A100 memory config, I believe most information can be found in its whitepaper. I don't know the exact TLB related numbers in A100, but I assume you can still use 512KB as L2 slice, 2 uTLB per tpc, and 2 L1 tlbs per gpc.

**Comment by Diksha-Moolchandani** [comment]
ok thanks

**Comment by Ruinhuang** [comment]
@Diksha-Moolchandani Hi, i'm also trying to make a a100.ini. could you share you a100.ini file? I want to check that some of my values ​​are consistent with yours. Thanks very much!

**Comment by Diksha-Moolchandani** [comment]
[a100.txt](https://github.com/user-attachments/files/16192949/a100.txt)
Let me know if these values make sense

**Comment by Ruinhuang** [comment]
@Diksha-Moolchandani thanks for sharing.  it's same as my formula.
